# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import threading

class Ui_StartupbyTim(object) :
    def setupUi(self, StartupbyTim) :
        StartupbyTim.setObjectName("StartupbyTim")
        StartupbyTim.resize(846, 628)
        self.centralwidget = QtWidgets.QWidget(StartupbyTim)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(640, 120, 151, 71))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.rununterhaltung)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 40, 241, 111))
        self.label.setMouseTracking(False)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(460, 120, 151, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.runstandard)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 120, 151, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.rungaming)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(110, 120, 151, 71))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.runschule)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 190, 241, 111))
        self.label_2.setMouseTracking(False)
        self.label_2.setObjectName("label_2")
        StartupbyTim.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StartupbyTim)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 846, 21))
        self.menubar.setObjectName("menubar")
        StartupbyTim.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StartupbyTim)
        self.statusbar.setObjectName("statusbar")
        StartupbyTim.setStatusBar(self.statusbar)

        self.retranslateUi(StartupbyTim)
        QtCore.QMetaObject.connectSlotsByName(StartupbyTim)

    def retranslateUi(self, StartupbyTim) :
        _translate = QtCore.QCoreApplication.translate
        StartupbyTim.setWindowTitle(_translate("StartupbyTim", "MainWindow"))
        self.pushButton.setText(_translate("StartupbyTim", "Unterhaltung"))
        self.label.setText(_translate("StartupbyTim", "Hallo welcher Modus willst du verwenden?"))
        self.pushButton_2.setText(_translate("StartupbyTim", "Standard"))
        self.pushButton_3.setText(_translate("StartupbyTim", "Gaming"))
        self.pushButton_4.setText(_translate("StartupbyTim", "Schule"))
        self.label_2.setText(_translate("StartupbyTim", "Geöffnet"))

    def rununterhaltung(self):
        run = threading.Thread(target=self.unterhaltung)
        run.start()

    def unterhaltung(self) :
        print('unterhaltung')
        self.label_2.setText("Unterhaltung wird geöffnet")
        os.system("F:\Programme\Twitch\Bin\Twitch.exe")
        self.label_2.setText("Öffne voice meeter")
        os.system("F:\Programme\VB\Voicemeeter\Voicemeeterpro.exe")

    def runstandard(self):
        runstandard = threading.Thread(target=self.standard)
        runstandard.start()

    def standard(self) :
        print('Standard')
        self.label_2.setText("Standard wird geöffnet")
        os.system("C:\Verknüpfungen\Microsoft.lnk")
        os.system("C:\Verknüpfungen\Discord.lnk")
        os.system("C:\Verknüpfungen\Cpi.lnk")
        os.system("C:\Verknüpfungen\music.lnk")
        os.system("F:\Programme\VB\Voicemeeter\Voicemeeterpro.exe")

    def rungaming(self):
        rungaming = threading.Thread(target=self.gaming)
        rungaming.start()

    def gaming(self) :
        print('Gaming')
        self.label_2.setText("Gaming wird geöffnet")
        os.system("F:\Programme\VB\Voicemeeter\Voicemeeterpro.exe")
        os.system("C:\Verknüpfungen\Epic.lnk")
        os.system("C:\Verknüpfungen\Discord.lnk")
        os.system("C:\Verknüpfungen\Rainway.lnk")

    def runschule(self):
        runschulle = threading.Thread(target=self.schule)
        runschulle.start()

    def schule(self) :
        print('Schule')
        self.label_2.setText("Schule wird geöffnet")
        os.system("C:\Verknüpfungen\Cpi.lnk")
        os.system('C:\Verknüpfungen\MicrosoftTeams.lnk')



if __name__ == "__main__" :
    import sys

    app = QtWidgets.QApplication(sys.argv)
    StartupbyTim = QtWidgets.QMainWindow()
    ui = Ui_StartupbyTim()
    ui.setupUi(StartupbyTim)
    StartupbyTim.show()
    sys.exit(app.exec_())
